import { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import { Header } from '../components/Header'

import '../styles/global.css'
import { twMerge } from 'tailwind-merge'

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  display: 'swap',
  style: ['normal', 'italic'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" className="h-full bg-petrol-900 antialiased">
      <body className={twMerge('pb-16', roboto.className)}>
        <Header />

        <main className="max-w-[1220px] h-full mx-auto mt-6">{children}</main>
      </body>
    </html>
  )
}
